

services:
  apache:
    build: .
    container_name: apache-container
    ports:
      - "8080:80"  # Puedes cambiar el puerto si es necesario
    volumes:
      - ./public:/var/www/html    # Archivos estáticos como HTML, CSS, JS
      - ./cgi-bin:/usr/lib/cgi-bin  # Scripts CGI (Perl)
      - ./apache-config:/etc/apache2/sites-enabled  # Configuración de Apache
    depends_on:
      - mariadb
    networks:
      - webnet
    restart: always

  mariadb:
    image: mariadb:10.5
    container_name: mariadb-container
    environment:
      MYSQL_ROOT_PASSWORD: santiago81
      MYSQL_DATABASE: finance_db  # Cambié el nombre de la base de datos a finance_db
      MYSQL_USER: root
      MYSQL_PASSWORD: santiago81
    volumes:
      - ./mariadb-data:/var/lib/mysql
    networks:
      - webnet
    restart: always

networks:
  webnet:
    driver: bridge
