
services:
  apache:
    build: .
    container_name: apache-container
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html
      - ./apache-config:/etc/apache2/sites-enabled
    depends_on:
      - mariadb
    networks:
      - webnet
    restart: always

  mariadb:
    image: mariadb:10.5
    container_name: mariadb-container
    environment:
      MYSQL_ROOT_PASSWORD: santiago81
      MYSQL_DATABASE: gestor_finanzas
      MYSQL_USER: root
      MYSQL_PASSWORD: santiago81
    volumes:
      - ./mariadb-data:/var/lib/mysql
      - ./gestor_finanzas.sql:/docker-entrypoint-initdb.d/gestor_finanzas.sql
    networks:
      - webnet
    restart: always

networks:
  webnet:
    driver: bridge
